### ISSUE TITLE
node_modules/@synatic/noql/node_modules/bson/lib/bson.mjs:142:28:    Unexpected reserved word 'await'. (142:28)

### ISSUE THREAD

**Issue by zeekun** [synatic/noql#162]
node_modules/@synatic/noql/node_modules/bson/lib/bson.mjs:142:28:
   Unexpected reserved word 'await'. (142:28)

This error appears in my meteor app that uses node version 14.21.3

**Comment by eXigentCoder** [comment]
Apologies that I could not get to this sooner, but I have just released version 3 of the library which should address this issue.
